/**
 * @module constants
 */
const ASTEROID_COLLISION_LAYER = 1;
const ASTEROID_BIG_SIZE = {min: 20, max: 50};
const ASTEROID_SMALL_SIZE = {min: 5, max: 20};
const ASTEROID_BIG_POINTS = {min: 20, max: 30};
const ASTEROID_SMALL_POINTS = {min: 10, max: 25};
const ASTEROID_DIVIDE_NUMBER = {min: 2, max: 4};
const ASTEROID_MAX_SPEED = 100;
const ASTEROID_MAX_ROTATION_SPEED = Math.PI;

const SHIP_COLLISION_LAYER = 2;
const SHIP_FIRE_RATE = 5;
const SHIP_SIZE = 15;
const SHIP_FIRE_COST = 10;
const SHIP_ENERGY_MAX = 100;
const SHIP_ENERGY_RECOVER_SPEED = 20;
const SHIP_THRUST = 100;
const SHIP_BREAK = 200;
const SHIP_FRICTION = 2;
const SHIP_EPSILON_SPEED = 0.1;
const SHIP_THRUST_PARTICLES_RATE = 100;
const SHIP_ROTATION_SPEED = Math.PI;

const BULLET_COLLISION_LAYER = 3;


export {
    ASTEROID_COLLISION_LAYER,
    ASTEROID_BIG_SIZE,
    ASTEROID_SMALL_SIZE,
    ASTEROID_BIG_POINTS,
    ASTEROID_SMALL_POINTS,
    ASTEROID_DIVIDE_NUMBER,
    ASTEROID_MAX_SPEED,
    ASTEROID_MAX_ROTATION_SPEED,
    SHIP_COLLISION_LAYER,
    BULLET_COLLISION_LAYER
}