'use strict';import{LayoutGravity as G}from"./layout.mjs";function mix(superclass,...mixins){class C extends superclass{}let len=mixins.length,i=-1;while(++i<len)merge(C.prototype,mixins[i],true);return C}function merge(out,src,override=false){for(let p in src)if(src.hasOwnProperty(p)&&(override||!out.hasOwnProperty(p)))out[p]=src[p]}const loadString=(url)=>new Promise((resolve)=>{const client=new XMLHttpRequest;client.open("GET",url);client.onreadystatechange=()=>{if(client.readyState===4&&client.status===
200||client.status===0)resolve(client.responseText)};client.send()});const loadXml=(url)=>{return loadString(url).then((text)=>{if(window.DOMParser)return(new DOMParser).parseFromString(text,"text/xml");else{const xmlDoc=new ActiveXObject("Microsoft.XMLDOM");xmlDoc.async=false;xmlDoc.loadXML(text);return xmlDoc}})};const loadImage=(url)=>new Promise((resolve)=>{const img=new Image;img.onload=()=>resolve(img);img.src=url});function createScriptWorker(script){const url=URL.createObjectURL(new Blob([script],
{type:"application/javascript"}));const worker=new Worker(url);URL.revokeObjectURL(url);return worker}function polyfill(container,name,vendors){for(let i=0;i<vendors.length&&!container[name];i++)container[name]=container[vendors[i]+name]||container[vendors[i]+name[0].toUpperCase()+name.substr(1)]}function waitForEvent(elmt,event){return new Promise((r)=>{object.addEventListener(event,r,{once:true})})}function delay(ms){return new Promise((r)=>setTimeout(r,ms))}function textFileUserDownload(text,fileName){let element=
document.createElement("a");element.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(text));element.setAttribute("download",fileName);element.style.display="none";document.body.appendChild(element);element.click();document.body.removeChild(element)}function BBCodeToHTML(bbCode){let str=bbCode;str=str.replace(/\[b](.+?)\[\/b]/g,"<b>$1</b>");str=str.replace(/\[br\/]/g,"");str=str.replace(/\[br]/g,"");str=str.replace(/\[i](.+?)\[\/i]/g,"<i>$1</i>");str=str.replace(/\[u](.+?)\[\/u]/g,
"<u>$1</u>");str=str.replace(/\[s](.+?)\[\/s]/g,"<s>$1</s>");str=str.replace(/\[code](.+?)\[\/code]/g,"<code>$1</code>");str=str.replace(/\[pre](.+?)\[\/pre]/g,"<code>$1</code>");str=str.replace(/\[style (.+?)](.+?)\[\/style]/g,"<font $1>$2</font>");str=str.replace(/\[size=(.+?)](.+?)\[\/size]/g,'<span style="font-size:$1px;">$2</span>');str=str.replace(/\[color=(.+?)](.+?)\[\/color]/g,'<span style="color:$1;">$2</span>');str=str.replace(/\[url=([^]+)](.+?)\[\/url]/g,'<a href="$1">$2</a>');str=str.replace(/\[url](.+?)\[\/url]/g,
'<a href="$1" target="_blank">$1</a>');str=str.replace(/\[img](.+?)\[\/img]/g,'<img src="$1" border="0">');return str}const loadWasmModule=(wasmUrl)=>WebAssembly.compileStreaming(fetch(wasmUrl));const instantiateWASM=(wasmUrl,imports)=>loadWasmModule(wasmUrl).then((module)=>WebAssembly.instantiate(module,imports));const rangedRandom=(min,max)=>Math.random()*(max-min)+min;const gaussianRandom=()=>(Math.random()+Math.random()+Math.random()+Math.random()+Math.random()+Math.random()-3)/3;class PRNG{constructor(seed){this.seed=
seed%2147483647;if(this.seed<=0)this.seed+=2147483646}next(){return this.seed=this.seed*16807%2147483647}nextRanged(min,max){return this.next()%(max-min)+min}nextFloat(){return(this.next()-1)/2147483646}nextRangedFloat(min,max){return this.nextFloat()*(max-min)+min}get randomIntFunction(){return this.next.bind(this)}get randomFloatFunction(){return this.nextFloat.bind(this)}}const wrapText=function(text,rect,lineHeight,textGravity,fill=true,stroke=false){const paragraphs=text.split("\n");const parLen=
paragraphs.length;const rectWidth=rect.width;let lines=[],line;let linesX=[],lineX=0;let words,len;let testLine;let metrics;let width=0;let n;for(let i=0;i<parLen;i++){words=paragraphs[i].split(" ");len=words.length;if(!len){lines.push(paragraphs[i]);linesX.push(0);continue}line=words[0];for(n=1;n<len;n++){testLine=line+" "+words[n];metrics=this.measureText(testLine);width=metrics.width;if(width>rectWidth&&n>0){lineX=rect.xMin;if(!(textGravity&G.LEFT))if(textGravity&G.RIGHT)lineX+=this.measureText(line).width-
width;else if(textGravity&G.CENTER)lineX+=(this.measureText(line).width-width)/2;lines.push(line);line=words[n];linesX.push(lineX)}else line=testLine}lineX=rect.xMin;if(!(textGravity&G.LEFT)){metrics=this.measureText(line);width=metrics.width;if(textGravity&G.RIGHT)lineX+=rectWidth-width;else if(textGravity&G.CENTER)lineX+=(rectWidth-width)/2}lines.push(line);linesX.push(lineX)}len=lines.length;let y=rect.yMin+lineHeight;if(!(textGravity&G.TOP))if(textGravity&G.BOTTOM)y=rect.yMax-lineHeight*(len-
1);else if(textGravity&G.CENTER)y+=(rect.height-lineHeight*len)/2;for(n=0;n<len;n++){if(fill)this.fillText(lines[n],linesX[n],y);if(stroke)this.strokeText(lines[n],linesX[n],y);y+=lineHeight}};const hashCode=function(string){const len=string.length;if(len===0)return 0;let hash=0;for(let i=0;i<len;++i){hash=(hash<<5)-hash+string.charCodeAt(i);hash=hash&hash}return hash};const listenDevToolsOpening=function(){return new Promise((r)=>{var devtools=/./;devtools.toString=function(){r()};console.log("%c",
devtools)})};const shuffleArray=function(array,randFunction=Math.random){return array.map((x)=>[randFunction(),x]).sort((a,b)=>a[0]-b[0]).map((x)=>x[1])};const createOneDimensionGaussianFunction=function(mu=0,sigma=1){const val_1=1/(sigma+Math.sqrt(2*Math.PI));const denom=-1/(2*sigma**2);const val_2=Math.exp(mu**2/(2*sigma**2));const factor=val_1*val_2;return(x)=>factor*Math.exp(x*denom)};export{mix,merge,loadString,loadXml,loadImage,createScriptWorker,polyfill,waitForEvent,delay,textFileUserDownload,
BBCodeToHTML,loadWasmModule,instantiateWASM,rangedRandom,gaussianRandom,PRNG,wrapText,hashCode,shuffleArray,listenDevToolsOpening,createOneDimensionGaussianFunction};
